### ISSUE TITLE
Неверное указание цвета

### ISSUE THREAD

**Issue by codebyzen** [ImangazalievM/CleanArchitectureManifest#5]
В тексте сказано
`Черными стрелками обозначены зависимости одних слоев от других, а красными - поток данных.`

Должно быть 
`Черными стрелками обозначены зависимости одних слоев от других, а синими - поток данных.`

**Comment by ImangazalievM** [comment]
Здравствуйте. Да, я в курсе) Исправлю в следующей редакции.
